version: '3.9'
services:
  backend:
    build: ./backend
    container_name: dailydo-backend
    ports:
      - "9090:9090"
    volumes:
      - ./backend:/app
      - ~/.gradle:/root/.gradle
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/dailydo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: dailydo-frontend
    ports:
      - "3009:3009"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:9090
      - PORT=3009
    depends_on:
      - backend
  db:
    image: mysql:8.0
    container_name: dailydo-db
    ports:
      - "4306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dailydo
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
